using System.ComponentModel;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace AddressablesGenerator
{
    /// <summary>
    /// Customizes logic for for groups generated by <see cref="AddressableGroupGenerator"/>
    /// </summary>
    /// <owner>jonagill</owner>
    [DisplayName("Generated Group Settings")]
    public class GeneratedGroupSettingsSchema : AddressableAssetGroupSchema
    {
        [SerializeField]
        [Tooltip("Groups with a higher priority can take assets specified in a group with a lower priority that tries to add the same assets. " +
                 "This value is auto-generated and should not be manually edited.")]
        public int Priority;
    }
}
